### PR TITLE
Architecture

### LINKED ISSUE #174: No statements for question answers
**Description**
If I choose randomized question from the quiz options, the plugin stops working as expected when sending question submitted statements.

**Version**
- ````$plugin->version = 2018022201;````

**Steps to reproduce the bug**
1. add multichoice question, add true false, and add another multichoice question
2. take a quiz with the above question types. Check LRS everything will be entering fine.
3. add a random question, and use the question bank from the quiz you just created.
4. take quiz.
5. when you return to see the results you will notice errors at the bottom of the page about undefined offset.
6. go to LRS and you will notice no questions have been sent and it will say only 'page viewed' or quiz attempt started.

**Expected behaviour**
- Questions to be sent to the LRS with out issue, regardless of random question. The results should be the same with the three question types even if they are in random order.

**Actual behaviour**
- Error, nothing is sent. 

**Server information**
- MySQL 5.7, php7.0 & php 7.1 Moodle 3.5 LearningLocker.

**Client information**
- OS: Windows Server 2017, windows 10
- Browser: Chrome, firefox, IE

**Additional information**
- One line 34 of QuestionSubmitted.php the call 
```` $question = $this->expand_question(
                $opts['questions'][$questionattempt->questionid],
                $opts['questions']
            );
````

is making a call to $questionattempt->questionid however, the questionid value is pointing to an index that is not in $opts[questions], for the random question array element, only the normal questions. which causes and undefined index error.

````
stdClass::__set_state(array(
   'id' => '16',
   'questionusageid' => '8',
   'slot' => '2',
   'behaviour' => 'deferredfeedback',
   'questionid' => '5',
   'variant' => '1',
   'maxmark' => '1.0000000',
   'minfraction' => '0.0000000',
   'maxfraction' => '1.0000000',
   'flagged' => '0',
   'questionsummary' => 'adding more stuff

',
   'rightanswer' => 'True',
   'responsesummary' => 'True',
   'timemodified' => '1530118034',
   'steps' => 
  array (
    44 => 
    stdClass::__set_state(array(
       'id' => '44',
       'questionattemptid' => '16',
       'sequencenumber' => '0',
       'state' => 'todo',
       'fraction' => NULL,
       'timecreated' => '1530118007',
       'userid' => '2',
       'data' => 
      array (
      ),
    )),
    47 => 
    stdClass::__set_state(array(
       'id' => '47',
       'questionattemptid' => '16',
       'sequencenumber' => '1',
       'state' => 'complete',
       'fraction' => NULL,
       'timecreated' => '1530118017',
       'userid' => '2',
       'data' => 
      array (
        57 => 
        stdClass::__set_state(array(
           'id' => '57',
           'attemptstepid' => '47',
           'name' => 'answer',
           'value' => '1',
        )),
      ),
    )),
    50 => 
    stdClass::__set_state(array(
       'id' => '50',
       'questionattemptid' => '16',
       'sequencenumber' => '2',
       'state' => 'gradedright',
       'fraction' => '1.0000000',
       'timecreated' => '1530118034',
       'userid' => '2',
       'data' => 
      array (
        62 => 
        stdClass::__set_state(array(
           'id' => '62',
           'attemptstepid' => '50',
           'name' => '-finish',
           'value' => '1',
        )),
      ),
    )),
  ),
))
````
So as you can see in the above array, questionid is set to 5, but the actual question in the array is 3. Causing an unknown index error.

### PR DESCRIPTION
**Pull request by caperneoignis**
Working progress, making fixes for warnings I'm getting, and trying to resolve #174 will notify when this is ready for merge. but adding a pull request so others can see what I'm doing and make recommendations.

### CODE REVIEW

File: version.php [hunk 1]
```diff
@@ -26,7 +26,7 @@
 
 defined('MOODLE_INTERNAL') || die();
 
-$plugin = $plugin ? $plugin : new StdClass();
+$plugin = isset($plugin) && is_object($plugin) ? $plugin : new StdClass();
```
Comment (ryasmi) [inline version.php:29]: Good idea.

File: src/transformer/utils/get_user.php [hunk 2]
```diff
@@ -2,9 +2,9 @@
 
 namespace src\transformer\utils;
 
-function get_user(array $config,  \stdClass $user) {
+function get_user(array $config, \stdClass $user) {
     $full_name = get_full_name($user);
-    if ($config['sendmbox'] == true) {
+    if (array_key_exists('sendmbox', $config) && $config['sendmbox'] == true) {
```
Comment (ryasmi) [inline src/transformer/utils/get_user.php:7]: Nice 👍

File: src/autoload.php [hunk 3]
```diff
@@ -2,7 +2,10 @@
 
 namespace src;
 
-define('MOODLE_INTERNAL', 1);
+// In Moodle this is set, however in testing this is not. So need to set it if not set or leave it be.
```
Comment (ryasmi) [inline src/autoload.php:5]: Interesting, what do you mean by "in testing"?

File: classes/log/store.php [hunk 4]
```diff
@@ -89,6 +89,7 @@ protected function insert_event_entries(array $events) {
     public function process_events(array $events) {
         global $DB;
         global $CFG;
+        require_once(__DIR__ . '/../../version.php');
```
Comment (ryasmi) [inline classes/log/store.php:92]: Any idea why that works that way but not the other? We have the plugin on a local Moodle 3.5 instance using the other way.

File: src/autoload.php (hunk 3 above)
Comment (caperneoignis) [reply src/autoload.php:5]: I thought that is why you guys had that there? Otherwise, I don't know why the code needs a redefine for 'moodle_internal'?

File: classes/log/store.php (hunk 4 above)
Comment (caperneoignis) [reply classes/log/store.php:92]: Great question, I'm running 7.0.6 on my local VM and it was throwing errors glore over that. 

Just like the tenery functions for names. ````$site_name = $site->fullname ? $site->fullname : 'A Moodle site';```` if you just leave it as ````$site_name = $site->fullname ?: 'A Moodle site';```` it returns null. Not sure why that is happening, from my understanding that later code line should return $fullname not null.

Comment (caperneoignis) [reply classes/log/store.php:92]: Actually, my VM is running windows. What are your dev machines running? There is a chance this is an OS specific issue. In which case, how do you want to handle it? Because this looks like this should work either way, the way I have it now. Windows may have a more strict bug checking because I have xdebug on the windows server.

File: src/autoload.php (hunk 3 above)
Comment (ryasmi) [reply src/autoload.php:5]: Ah sorry, yeah you're totally right.

File: classes/log/store.php (hunk 4 above)
Comment (ryasmi) [reply classes/log/store.php:92]: Not sure about the ternary's, don't mind changing those ternary's to stop using `?:` that's fine. Just not sure why the `require_once` is causing a problem for that particular file, but not the other one above it `require_once(__DIR__ . '/../../src/autoload.php');`. We're using Mac and Ubuntu mostly here by the way, not sure if that makes a difference.

File: src/transformer/events/mod_quiz/attempt_reviewed.php [hunk 5]
```diff
@@ -9,7 +9,9 @@ function attempt_reviewed(array $config, \stdClass $event) {
     $learner = $repo->read_record_by_id('user', $event->relateduserid);
     $instructor = $repo->read_record_by_id('user', $event->userid);
     $course = $repo->read_record_by_id('course', $event->courseid);
-    $attempt = $repo->read_record_by_id('attempt', $event->objectid);
+    $attempt = $repo->read_record_by_id('quiz_attempts', $event->objectid);
+    // Quiz attempts don't have names, so this will resolve an issue with the batch send to the LRS later.
+    $attempt->name = 'attempt reviewed';
```
Comment (ryasmi) [inline src/transformer/events/mod_quiz/attempt_reviewed.php:14]: Is the missing attempt name causing an issue on Line 48 in the `context.contextActivities.grouping`? If so I think a better solution would be to make a new util to replace line 48 with something like `utils\get_activity\attempt($config, $attempt, $lang)`. This could then be reused elsewhere to fix the issue in a single function in all uses. Hope that makes sense.

File: src/transformer/utils/get_full_name.php [hunk 6]
```diff
@@ -12,7 +12,7 @@ function get_full_name(\stdClass $user) {
     if ($has_first_name) {
         return $user->firstname;
     }
-    if ($has_lastname_name) {
+    if ($has_last_name) {
```
Comment (ryasmi) [inline src/transformer/utils/get_full_name.php:15]: Good find, amazed I managed to do that, must have been a dodgy name refactor.

**Review by ryasmi — CHANGES_REQUESTED** [review]

**Comment by ryasmi** [comment]
Really appreciate you taking the time to dig through this @caperneoignis! 👍

File: src/transformer/utils/get_full_name.php (hunk 6 above)
Comment (caperneoignis) [reply src/transformer/utils/get_full_name.php:15]: Yea, it looked a bit weird when I saw it, thought maybe it was a variable done later, but didn't see it, so I went ahead and changed it to what I thought it should be.

**Comment by caperneoignis** [comment]
No problem @ryansmith94 I need this for a project, so I got time to really sort through this and get it a bit further along for yea.

File: src/transformer/events/mod_quiz/attempt_reviewed.php (hunk 5 above)
Comment (caperneoignis) [reply src/transformer/events/mod_quiz/attempt_reviewed.php:14]: Yea! That was definitely a fix to get me along to the next issue. Till I found a better way to do it. I will make another util and add it where the $attempt->name is called, I believe it is really just that one return. In which case I'll add the function call there and have a function with a check to see if name is set and if not run it through a switch statement to find the best name depending on the activity table. Shouldn't be too hard and should be much cleaner then what I'm doing now. I'll hit it Monday, if the urge doesn't strike over the weekend.

**Comment by ryasmi** [comment]
That's awesome, really appreciated! 👍

File: src/transformer/events/mod_quiz/attempt_reviewed.php (hunk 5 above)
Comment (ryasmi) [reply src/transformer/events/mod_quiz/attempt_reviewed.php:14]: No worries, thought as much. Okay sounds good 👍

File: src/transformer/utils/get_full_name.php (hunk 6 above)
Comment (ryasmi) [reply src/transformer/utils/get_full_name.php:15]: Haha thanks

**Comment by caperneoignis** [comment]
yea, that's fine, I'll start doing the util
